医疗爬虫代码提交
sibbay-ai/data-sym-scrapy pull request #2
Opened 2017-11-26 06:25 UTC by cyssxt

2017-11-28 02:20 UTC, fushang318 commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@cyssxt  .idea 目录需要加到 .gitignore 忽略

2017-11-28 02:20 UTC, fushang318 commented on core/__init__.py
> +sys.setdefaultencoding('utf-8')
@cyssxt 在 README.md 注明一下python 的版本要求吧

2017-11-28 02:20 UTC, fushang318 commented on core/__init__.py
> +sys.setdefaultencoding('utf-8')
@cyssxt 需要在项目里增加一个 requirements.txt 文件声明一下需要的 python 库依赖

2017-11-28 02:20 UTC, fushang318 commented on utils/ExcelUtils.py
> +# coding=utf-8
@cyssxt python 脚本的文件命名需要全小写，单词之间用下划线连接

2017-11-28 02:20 UTC, fushang318 commented on utils/NetTools.py
> +# coding=utf-8
@cyssxt python 脚本的文件命名需要全小写，单词之间用下划线连接

2017-11-28 17:31 UTC, sinchb requested changes
* 我看代码还是使用Python2语法，如果没有特殊要求，尽量都改为Python3吧
* 代码风格需要 **严格** 遵守 [PEP8规范](https://www.python.org/dev/peps/pep-0008/)
@cyssxt

2017-11-28 17:31 UTC, sinchb commented on README.md
> +是程序启动文件
如何启动需要有明确的shell命令指明，包括参数，例如

```bash
python start.py xxx yyy
```
@cyssxt

2017-11-28 17:31 UTC, sinchb commented on core/__init__.py
> +sys.setdefaultencoding('utf-8')
@cyssxt @fushang318 我们不是用Python3.6么，Python3的话，包括coding和reload(sys)都不需要

2017-11-29 01:39 UTC, fushang318 commented on core/__init__.py
> +sys.setdefaultencoding('utf-8')
@sinchb 这个 ... @georgeliuyu 创建这个ISSUE时，没有说明必须使用 python3.6。。

2017-11-29 01:40 UTC, fushang318 commented
@sinchb @georgeliuyu 因为创建这个ISSUE时，并没有要求使用 python3.6
现在需要 @cyssxt 修改到 python3 的话，我认为需要增加额外的工作量和ICP时间评估吧  
你们认为呢

2017-11-29 01:48 UTC, cyssxt commented
我先把命名改下

2017-11-29 01:51 UTC, georgeliuyu commented
@cyssxt 建议改为python3

2017-11-29 03:18 UTC, cyssxt commented
@georgeliuyu @fushang318 @sinchb 我改下python3把 主要基于我之前开发的项目都是python2.7

2017-11-29 03:59 UTC, fushang318 commented
@cyssxt 好的，小白目前python 代码都是基于 python3.6的

2017-11-29 16:49 UTC, sinchb commented
@georgeliuyu 没问题，工作量是要增加的
@cyssxt 请评估Python2-> Python3.6的工作量。

2017-11-30 01:53 UTC, cyssxt commented
0.5D

2017-11-30 15:13 UTC, sinchb commented
@cyssxt 重新提交后，@ 下我哈

2017-12-01 16:10 UTC, sinchb requested changes

2017-12-01 16:10 UTC, sinchb commented on core/__init__.py
> +import threading
Python3不需要 coding=utf-8 @cyssxt

2017-12-01 16:10 UTC, sinchb commented on core/__init__.py
> +import threading
reload这些代码可以删除了

2017-12-01 16:10 UTC, sinchb commented on core/__init__.py
> +    def __init__(self, thread_num=None,finish=None):
``thread_num=None,``后面需要一个空格 @cyssxt

2017-12-01 16:10 UTC, sinchb commented on core/__init__.py
> +        self.execute_num = self.execute_num-1
```python
self.execute_num = self.execute_num - 1
```

```python
self.execute_num -= 1
```

2017-12-01 16:10 UTC, sinchb commented on core/__init__.py
> +        if len(self.buffer_schedule) is not 0:
更加Pythonic的写法

```python
if self.buffer_schedule:
    xxxx
```

2017-12-01 16:10 UTC, sinchb commented on core/__init__.py
> +        if self.execute_num==0 and len(self.buffer_schedule) is 0:
同上 @cyssxt

2017-12-01 16:10 UTC, sinchb commented on core/__init__.py
> +        return True if self.execute_num >= self.thread_num else False
```python
return self.execute_num >= self.thread_num 
```

2017-12-01 16:10 UTC, sinchb commented on start.py
> +translateUrl = net_tools.Url('http://translate.google.cn/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=google')
python里变量命名
* 局部变量: 小写加下划线
* 全局变量：大写加下划线

2017-12-01 16:10 UTC, sinchb commented on start.py
> +        url, table, row, index, title = args
如果args里的字段是确定的，为什么不将参数拆分，通过 ``run`` 来传入呢？

```python
run(self, url, table, row, index, title)
```

2017-12-01 16:10 UTC, sinchb commented on start.py
> +        if matches and len(matches) > 0:
```python
if matches:
    xxxx
```

2017-12-01 16:10 UTC, sinchb commented on start.py
> +            # print url.url, title, conceptId
这个elif的block很奇怪。看起来这一行代码似乎是不需要的

```python
elif title.endswith("s") or title.endswith("es"):
```

另外无用的comment和这个pass也可以删掉了
@cyssxt

2017-12-01 16:10 UTC, sinchb commented on start.py
> +# 翻译title,about任务
将类似这样的comment转换为 docstring  会非常好 @cyssxt

2017-12-01 16:10 UTC, sinchb commented on start.py
> +        if result != None and len(result) > 0:
```python
if result != None and len(result) > 0:
```
->

```python
if result:
```

这样是不是可以？ @cyssxt 

我看整个pr里有很多类似的代码，统一改掉吧

2017-12-01 16:10 UTC, sinchb commented on start.py
> +        translate_url, table, row, index, title = args
我看你Task.run里的的args的结构似乎都一样，可以统一一下。

2017-12-01 16:10 UTC, sinchb commented on start.py
> +        if ctitle!='' and cabout!="":
这里 为什么 不为空就返回？ @cyssxt

2017-12-01 16:10 UTC, sinchb commented on start.py
> +        if ctitle!='' and cabout!="":
另外， 字符串统一使用单引号吧 @cyssxt

2017-12-05 17:20 UTC, sinchb requested changes
* 上次comment中提到的未全部修改完，PEP8并未全部遵循
* 代码 / 注释 比过高，注释和docstr数量太少。
* magic number 过多，代码可读性不高。
* 代码中不允许出现被comment的代码，无用代码必须全部删除。  @cyssxt

2017-12-05 17:20 UTC, sinchb commented on .gitignore
> +/.idea/
添加gitignore后，需要将 .idea文件删除。

2017-12-06 00:34 UTC, cyssxt commented on .gitignore
> +/.idea/
谢谢了！今天会全部改完！

2017-12-06 00:36 UTC, cyssxt commented on core/__init__.py
> +import threading
修改

2017-12-06 00:36 UTC, cyssxt commented on core/__init__.py
> +    def __init__(self, thread_num=None,finish=None):
修改

2017-12-06 00:36 UTC, cyssxt commented on core/__init__.py
> +        self.execute_num = self.execute_num-1
修改

2017-12-06 00:37 UTC, cyssxt commented on core/__init__.py
> +        if len(self.buffer_schedule) is not 0:
修改

2017-12-06 00:38 UTC, cyssxt commented on core/__init__.py
> +        return True if self.execute_num >= self.thread_num else False
修改

2017-12-06 00:39 UTC, cyssxt commented on start.py
> +        url, table, row, index, title = args
这样的考虑是为了配合线程调用的参数的参数的传入

2017-12-06 00:57 UTC, cyssxt commented on start.py
> +        if matches and len(matches) > 0:
修改

2017-12-06 01:01 UTC, cyssxt commented on start.py
> +            # print url.url, title, conceptId
这两个条件具备同样的处理逻辑
TranslateTask().run(TRANSLATE_URL, table, row, index, title)

2017-12-06 01:02 UTC, cyssxt commented on start.py
> +        translate_url, table, row, index, title = args
这个主要是因为相符合线程执行 而这样设计的

2017-12-06 18:11 UTC, sinchb commented on start.py
> +        translate_url, table, row, index, title = args
线程执行也支持*args和**kwargs类似的参数传入 @cyssxt

2017-12-10 12:49 UTC, sinchb approved these changes

2017-12-10 12:55 UTC, sinchb requested changes

2017-12-10 12:55 UTC, sinchb commented on myapp.log
> +
日志文件不能提交 @cyssxt

2017-12-10 12:55 UTC, sinchb commented on start.py
> +
docstr 不是写在这里的 @cyssxt

2017-12-10 12:55 UTC, sinchb commented on test.py
> +    print(1)
这个文件是用来作什么的？ @cyssxt

2017-12-10 12:55 UTC, sinchb commented on utils/excel_utils.py
> +    def __init__(self, path, sheet=0, head_index=0, callback=None, offset=0, limit=None, desc_name="aaa.xls"):
desc_name的默认值很奇怪，没有什么意义 @cyssxt

2017-12-10 12:55 UTC, sinchb commented on utils/excel_utils.py
> +        end = (self.limit + start) if None is not self.limit else self.nrows
这句的条件 ``if None is not self.limit`` 是这个意思么：

```python
if self.limit
```
 @cyssxt

2017-12-10 12:55 UTC, sinchb commented on utils/excel_utils.py
> +    def get_cell_value(self, row_index, header):
docstr是必须写在method下面的。 @cyssxt

2017-12-10 12:55 UTC, sinchb commented on utils/excel_utils.py
> +# print nRows
这两行删除吧。

2017-12-10 12:55 UTC, sinchb commented on utils/net_tools.py
> +from urllib.parse import quote
import 的顺序和PEP8不符合。 @cyssxt

2017-12-10 12:55 UTC, sinchb commented on .idea/vcs.xml
> +  </component>
这个 .idea 删了么？ @cyssxt

2017-12-10 12:55 UTC, sinchb commented on core/__init__.py
> +# coding=utf-8
这个还是没有删除。 @cyssxt

2017-12-11 00:42 UTC, georgeliuyu commented on utils/net_tools.py
> +from urllib.parse import quote
@cyssxt 建议你采用标准的检查工具

2017-12-11 03:23 UTC, sinchb commented on utils/net_tools.py
> +from urllib.parse import quote
使用Pylint @cyssxt

2017-12-11 12:55 UTC, cyssxt commented on utils/net_tools.py
> +from urllib.parse import quote
哦  我用的pycharm的

2017-12-11 16:57 UTC, sinchb commented on utils/net_tools.py
> +from urllib.parse import quote
@cyssxt 建议仔细阅读PEP8，我上面有链接记得 https://www.python.org/dev/peps/pep-0008/

2018-01-03 11:08 UTC, sinchb commented
@fushang318 @cyssxt @georgeliuyu 所以，这个还要继续么

2018-01-03 12:48 UTC, georgeliuyu commented
@cyssxt 什么情况？  
@sinchb  如果明天没有答复，可按照icp的超市处理。

2018-01-07 15:08 UTC, sinchb commented
@georgeliuyu 这个close了。

2018-01-07 15:11 UTC, sinchb commented
@ben7th
我打了一个超时的Label

2018-01-07 15:11 UTC, closed without merging